#!/usr/bin/env bash
TYPE=$2
[ "$2" == "" ] && TYPE="zip"

filename=$(basename -- "$(realpath $1)")
extension="${filename##*.}"
filename="${filename%.*}"

cencode --input $1 --type $TYPE
scompress --input $filename.pb
cdecode --input $filename.compressed.pb